- name: Change Description on Interfaces
  cisco.ios.ios_interfaces:
    config:
      - name: GigabitEthernet1
        description: "Hello_GE1"

- name: Configure the login banner
  cisco.ios.ios_banner:
    banner: login
    text: "Any Damn Thing 11"
    state: present

- name: Configure the motd banner
  cisco.ios.ios_banner:
    banner: motd
    text: "Good Morning"
    state: present

- name: Configure a Cisco IOS device
  cisco.ios.ios_config:
    lines:
      - service timestamps debug datetime msec
      - service timestamps log datetime msec localtime
    save_when: changed
