galaxy_info:
  author: Diana M
  description: Ansible Developer
  company: SAP
  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1
  galaxy_tags: []

dependencies:
  - role: info_ios
