- name: Collect Facts Manually
  cisco.ios.ios_facts:
    gather_subset: all
  
- name: Create Folder to Store System Info
  ansible.builtin.file:
    path: ./sys_info/
    state: directory
    mode: '0755'

- name: Print Facts for Cisco Device
  ansible.builtin.copy:
    dest: ./sys_info/{{ inventory_hostname }}.txt
    content: |
   
      API           = {{ ansible_net_api }}
      Hostname      = {{ ansible_facts.net_hostname }}
      Type          = {{ ansible_facts['net_iostype'] }}
      Model         = {{ ansible_facts['net_model'] }}
      Serial Number = {{ ansible_facts['net_serialnum'] }}
      OS            = {{ ansible_facts['net_system'] }}
      OS Version    = {{ ansible_facts['net_version'] }}

- name: Just Print
  ansible.builtin.debug:
    msg: "Hello"
